mindmap
  root((Aminul<br/>Shamim))
    Industry
      Summit AS58717
        Deputy Manager
        8Tbps gateway
        Cisco NCS 9000
        Huawei NE-40E
      BDCOM 2012-2021
        MAXIM AAA
        700 resellers
      Peers
        TATA Bharti NTT
        RETN Equinix
    Depth
      Expert
        BGP MPLS
        DDoS mitigation
      Proficient
        SRv6
        AI/ML NetOps
      Learning
        Rust
        Product
    Community
      bdNOG Instructor
      SANOG APNIC
    Credentials
      M.Sc. PMICS DU
      CCNP CCNP-Sec
      RHCE JNCIA CNSS
