timeline
    title Career Timeline
    2007 : SSC Vocational
    2011 : Diploma CSE
    2012 : BDCOM Intern
    2014 : Junior Engineer
         : 32 bank networks
    2018 : Network Engineer
         : MAXIM AAA 700 resellers
    2021 : Summit Deputy Manager
    2024 : M.Sc. PMICS DU
    2026 : 8Tbps gateway
         : AI DDoS mitigation
